# render.yaml for Node.js Game Server
# This file tells Render how to deploy your server

services:
  - type: web # This specifies that it's a web service (your server)
    name: zombie-game-server # A friendly name for your service on Render
    env: node # The environment for your service (Node.js)
    plan: free # Use the free tier for testing (can be changed later)
    # The command to install dependencies
    buildCommand: npm install
    # The command to start your server
    startCommand: node server.js
    # Health check path (optional but recommended for production)
    healthCheckPath: /health
    # Environment variables are defined here, including the PORT that your server.js reads
    envVars:
      - key: PORT
        value: "3000" # Define PORT as an environment variable with string value
      # Example of other environment variables if you needed them:
      # - key: MY_API_KEY
      #   value: mysecretkey
